ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

exclude: (?:^extern/)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.6.0'
    hooks:
      - id: end-of-file-fixer
        exclude: |
          (?x)^(
            ^.*\.ai|
            ^.*\.txt\
            ^extern/
          )
      - id: trailing-whitespace
        exclude: |
          (?x)^(
            ^.*\.ai|
            ^.*\.txt|
            ^extern/|
            ^setup.cfg
          )
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: requirements-txt-fixer
  - repo: https://github.com/glotzerlab/fix-license-header
    rev: v0.4.0
    hooks:
      - id: fix-license-header
        name: Fix License Headers (Python)
        exclude: |
          (?x)(
              ^doc/|
              ^extern/|
              ^requirements/
              )
        types_or: [c, c++, python]
        args:
          - --license-file=LICENSE
          - --start=2
          - --num=1
          - --add=This file is from the freud project, released under the BSD 3-Clause License.
          - --keep-before=#!
  - repo: https://github.com/asottile/pyupgrade
    rev: 'v3.16.0'
    hooks:
      - id: pyupgrade
        args:
          - --py36-plus
  - repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: '24.4.2'
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: '7.0.0'
    hooks:
      - id: flake8
        types: ["file"]
        types_or: ["python", "cython"]
        additional_dependencies: ["flake8-force"]
        args:
        - --show-source
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v18.1.6'
    hooks:
      - id: clang-format
        types_or: [c, c++]
# The following pre-commit hooks should only be run manually because they have
# dependencies that cannot be pip installed.
  - repo: local
    hooks:
    - id: clang-tidy
      stages: [manual]  # Requires clang-tidy.
      name: clang-tidy
      entry: clang-tidy-18
      language: system
      types: [c++]
      # Exclude external files.
      # TODO: remove exlcusions for modules as they are ported to nanobind
      exclude: |
        (?x)^(
          ^extern/|
          ^freud/cluster/|
          ^freud/density/|
          ^freud/diffraction/|
          ^freud/environment/|
          ^freud/order/
        )
      args:
      - --warnings-as-errors=*
