version: 2
build:
    os: ubuntu-22.04
conda:
    environment: doc/readthedocs-env.yml
python:
    install:
        - method: setuptools
          path: .
submodules:
    include: all
    recursive: true
