blank_issues_enabled: true
contact_links:
  - name: freud discussion board
    url: https://github.com/glotzerlab/freud/discussions/
    about: Ask the freud user community for help.
  - name: freud documentation
    url: https://freud.readthedocs.io/
    about: User documentation.
