name: Feature Request
description: Suggest a new feature for freud
labels: ['enhancement']
body:
  - type: textarea
    attributes:
      label: Description
      description: What new feature would be useful to add to freud?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Solution
      description: How should this new feature be implemented? What should a script using this feature look like?
    validations:
      required: true
  - type: textarea
    attributes:
        label: Additional Context
        description: What additional information is useful to understand this request?
  - type: dropdown
    attributes:
      label: Developer
      description: Who should implement the new feature?
      options:
        - I will submit a pull request that implements this feature.
        - Would someone else please implement this?
