name: Run Unit Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  # trigger on pull requests
  pull_request:

  # trigger on all commits to trunk branches
  push:
    branches:
      - "main"
      - "next"

  # trigger on request
  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  run_tests:
    name: Run tests on ${{ matrix.os }} with Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['39', '310', '311', '312']
        include:
          # Test macOS and windows on oldest and latest versions.
          - os: 'macos-14'
            python: '312'
          - os: 'windows-latest'
            python: '312'
          - os: 'windows-latest'
            python: '39'
          - os: 'macos-14'
            python: '39'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - name: Create Python Environment
        uses: mamba-org/setup-micromamba@v1.8.1
        with:
          micromamba-version: '1.5.8-0'
          environment-name: test
          environment-file: .github/workflows/env-files/py${{ matrix.python }}-conda-lock.yml

      - name: Build and Install freud
        run: |
          uv pip install . --no-build-isolation --no-deps -v

      - name: Run Tests
        run: |
          pytest tests/ -v
