name: style

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

  push:
    branches:
      - "main"
      - "nanobind"

  workflow_dispatch:

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  clang-tidy:
    name: Check C++ Code Style
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true
      - name: Create Python Environment
        uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1.9.0
        with:
          micromamba-version: '1.5.8-0'
          environment-name: test
          environment-file: .github/workflows/environments/py313-conda-lock.yml
      - name: Configure compile_commands.json
        run: |
          cmake -S . -B build -GNinja -DCMAKE_EXPORT_COMPILE_COMMANDS=True
      - name: clang-tidy
        run: pre-commit run clang-tidy --all-files --hook-stage=manual -v
