name: Update conda lockfiles

on:
  schedule:
    - cron: '9 12 */100,1-7 3,6,2,12 4'

  workflow_dispatch:

jobs:
  update:
    uses: glotzerlab/workflows/.github/workflows/update-conda-lockfiles.yaml@1855eec25e87bdbc06359aa3adc355b59272cae3 # 0.7.0
    secrets: inherit
    with:
      branch: main
